---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  become: true
  hosts: localhost
  roles:
    - common

- name: configure, deploy and run the go microservice
  become: true
  hosts: localhost
  roles:
    - web